- configuration: default
- username: admin
- password: bk123456
- ip: 192.168.0.105
- port: 554
- device number: '01'
- delay time: 5
- test calibration: false
- write debug info: false
- debug file location: data_process/debug
